#! /usr/bin/python
"""Search guppi files for fast radio bursts.

"""

import time
import argparse
from os import path

from burst_search import guppi


# Command line arguments.
parser = argparse.ArgumentParser(description='Search GUPPI data for FRBs.')
parser.add_argument("files", metavar="GUPPI_files", type=str, nargs='+',
                    help="GUPPI PSRFITS files to search.")

if __name__ == "__main__":
    args = parser.parse_args()

    for filename in args.files:
        guppi.search_file(filename)


